langgraph dev can't use memory
version] A newer version of langgraph-api is available: 0.5.39 → 0.6.16  (pip install -U langgraph-api)
2025-12-31T06:11:50.121330Z [info     ] [version] A newer version of langgraph-api is available: 0.5.39 → 0.6.16  (pip install -U langgraph-api) [version_check] api_revision=212ad47 api_variant=local_dev langgraph_api_version=0.5.39 message='[version] A newer version of langgraph-api is available: 0.5.39 → 0.6.16  (pip install -U langgraph-api)' thread_name='Thread-3 (_check_newer_version)'
⚠️ [support] langgraph-api 0.5.39 is in Critical support.
Only critical security and installation fixes are provided.
You are one minor version behind the latest (0.6.x).
Please plan an upgrade soon. See changelog: https://docs.langchain.com/langgraph-platform/langgraph-server-changelog
2025-12-31T06:11:50.121554Z [info     ] ⚠️ [support] langgraph-api 0.5.39 is in Critical support.
Only critical security and installation fixes are provided.
You are one minor version behind the latest (0.6.x).
Please plan an upgrade soon. See changelog: https://docs.langchain.com/langgraph-platform/langgraph-server-changelog [version_check] api_revision=212ad47 api_variant=local_dev langgraph_api_version=0.5.39 message='⚠️ [support] langgraph-api 0.5.39 is in Critical support.\nOnly critical security and installation fixes are provided.\nYou are one minor version behind the latest (0.6.x).\nPlease plan an upgrade soon. See changelog: https://docs.langchain.com/langgraph-platform/langgraph-server-changelog' thread_name='Thread-3 (_check_newer_version)'
2025-12-31T06:11:50.231439Z [info     ] Using langgraph_runtime_inmem  [langgraph_runtime] api_revision=212ad47 api_variant=local_dev langgraph_api_version=0.5.39 thread_name=MainThread
2025-12-31T06:11:50.244149Z [info     ] Using auth of type=noop        [langgraph_api.auth.middleware] api_revision=212ad47 api_variant=local_dev langgraph_api_version=0.5.39 thread_name=MainThread
2025-12-31T06:11:50.251601Z [info     ] Starting In-Memory runtime with langgraph-api=0.5.39 and in-memory runtime=0.20.1 [langgraph_runtime_inmem.lifespan] api_revision=212ad47 api_variant=local_dev langgraph_api_version=0.5.39 langgraph_runtime_inmem_version=0.20.1 thread_name=ThreadPoolExecutor-1_0 version=0.5.39
2025-12-31T06:11:50.316654Z [info     ] Starting thread TTL sweeper with interval 5 minutes [langgraph_api.thread_ttl] api_revision=212ad47 api_variant=local_dev interval_minutes=5 langgraph_api_version=0.5.39 strategy=delete thread_name=ThreadPoolExecutor-1_1
2025-12-31T06:11:51.081576Z [error    ] Graph 'my_agent' failed to load: ValueError: Heads up! Your graph 'app' from './agent.py' includes a custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>). With LangGraph API, persistence is handled automatically by the platform, so providing a custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>) here isn't necessary and will be ignored when deployed.

To simplify your setup and use the built-in persistence, please remove the custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>) from your graph definition. If you are looking to customize which postgres database to connect to, please set the `POSTGRES_URI` environment variable. See https://langchain-ai.github.io/langgraph/cloud/reference/env_var/#postgres_uri_custom for more details. [langgraph_runtime_inmem.lifespan] action=fix_user_graph api_revision=212ad47 api_variant=local_dev error_boundary=user_graph error_message="ValueError: Heads up! Your graph 'app' from './agent.py' includes a custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>). With LangGraph API, persistence is handled automatically by the platform, so providing a custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>) here isn't necessary and will be ignored when deployed.\n\nTo simplify your setup and use the built-in persistence, please remove the custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>) from your graph definition. If you are looking to customize which postgres database to connect to, please set the `POSTGRES_URI` environment variable. See https://langchain-ai.github.io/langgraph/cloud/reference/env_var/#postgres_uri_custom for more details." error_type=ValueError graph_id=my_agent langgraph_api_version=0.5.39 location=./agent.py summary="ValueError: ValueError: Heads up! Your graph 'app' from './agent.py' includes a custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>). With LangGraph API, persistence is handled automatically by the platform, so providing a custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>) here isn't necessary and will be ignored when deployed.\n\nTo simplify your setup and use the built-in persistence, please remove the custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>) from your graph definition. If you are looking to customize which postgres database to connect to, please set the `POSTGRES_URI` environment variable. See https://langchain-ai.github.io/langgraph/cloud/reference/env_var/#postgres_uri_custom for more details." thread_name=ThreadPoolExecutor-1_1 user_traceback='Traceback (most recent call last):\n  File "/api/langgraph_api/graph.py", line 420, in collect_graphs_from_env\n  File "/api/langgraph_api/utils/config.py", line 145, in run_in_executor\n  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File "/api/langgraph_api/utils/config.py", line 136, in wrapper\n  File "/api/langgraph_api/graph.py", line 545, in _graph_from_spec\nValueError: Heads up! Your graph \'app\' from \'./agent.py\' includes a custom checkpointer (type <class \'langgraph.checkpoint.memory.InMemorySaver\'>). With LangGraph API, persistence is handled automatically by the platform, so providing a custom checkpointer (type <class \'langgraph.checkpoint.memory.InMemorySaver\'>) here isn\'t necessary and will be ignored when deployed.\n\nTo simplify your setup and use the built-in persistence, please remove the custom checkpointer (type <class \'langgraph.checkpoint.memory.InMemorySaver\'>) from your graph definition. If you are looking to customize which postgres database to connect to, please set the `POSTGRES_URI` environment variable. See https://langchain-ai.github.io/langgraph/cloud/reference/env_var/#postgres_uri_custom for more details.\n'
2025-12-31T06:11:51.082792Z [info     ] Shutting down remote graphs    [langgraph_api.graph] api_revision=212ad47 api_variant=local_dev langgraph_api_version=0.5.39 thread_name=MainThread
2025-12-31T06:11:51.148488Z [error    ] Traceback (most recent call last):
  File "/api/langgraph_api/graph.py", line 420, in collect_graphs_from_env
  File "/api/langgraph_api/utils/config.py", line 145, in run_in_executor
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/api/langgraph_api/utils/config.py", line 136, in wrapper
  File "/api/langgraph_api/graph.py", line 545, in _graph_from_spec
ValueError: Heads up! Your graph 'app' from './agent.py' includes a custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>). With LangGraph API, persistence is handled automatically by the platform, so providing a custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>) here isn't necessary and will be ignored when deployed.

To simplify your setup and use the built-in persistence, please remove the custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>) from your graph definition. If you are looking to customize which postgres database to connect to, please set the `POSTGRES_URI` environment variable. See https://langchain-ai.github.io/langgraph/cloud/reference/env_var/#postgres_uri_custom for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 694, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/langgraph_runtime_inmem/lifespan.py", line 106, in lifespan
    await graph.collect_graphs_from_env(True)
  File "/api/langgraph_api/graph.py", line 422, in collect_graphs_from_env
langgraph_api.utils.errors.GraphLoadError: Failed to load graph 'my_agent' from ./agent.py: Heads up! Your graph 'app' from './agent.py' includes a custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>). With LangGraph API, persistence is handled automatically by the platform, so providing a custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>) here isn't necessary and will be ignored when deployed.

To simplify your setup and use the built-in persistence, please remove the custom checkpointer (type <class 'langgraph.checkpoint.memory.InMemorySaver'>) from your graph definition. If you are looking to customize which postgres database to connect to, please set the `POSTGRES_URI` environment variable. See https://langchain-ai.github.io/langgraph/cloud/reference/env_var/#postgres_uri_custom for more details.
 [uvicorn.error] api_revision=212ad47 api_variant=local_dev langgraph_api_version=0.5.39 thread_name=MainThread
2025-12-31T06:11:51.148640Z [error    ] Application startup failed. Exiting. [uvicorn.error] api_revision=212ad47 api_variant=local_dev langgraph_api_version=0.5.39 thread_name=MainThread